[dev]
base="./"
command="npm run start"

[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "*"

  [[redirects]]
  from = "/fr/home"
  to = "/fr/maintenance"
  status = 301
  force = true
  
    [[redirects]]
  from = "/fr/"
  to = "/fr/maintenance"
  status = 301
  force=true
  
[[redirects]]
  from = "/"
  to = "/fr/maintenance"
  status = 301
  force = true