[dev]
base="./"
command="npm run start"
publish="public/"

[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "*"


[[redirects]]
  from = "/"
  to = "/en/"
  status = 301
  force = true
[[redirects]]
from = "/*"
to = "/en/index.html"
status = 200
force = false

 