[dev]
base="./"
command="npm run start"

[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/fr/maintenance"
  status = 301
  force = true
  conditions = { Language = ["fr","fr-fr","fr-ca"] }
 [[redirects]]
  from = "/*"
  to = "/en/maintenance"
  status = 301
  force = true

