# Name of workflow
name: Development workflow

# When workflow is triggered
on:
  pull_request:
    branches:
      - dev

# Jobs to carry out
jobs:
  deploy-dev:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      # Install NodeJS
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16.x
          cache: "pnpm"

      - run: pnpm install
      - run: echo GATSBY_PORTFOLIO_RECAPTCHA_KEY= ${{ secrets.RECAPTCHA_KEY }} >> .env.production && yarn run build
      - name: Deploy to netlify
        uses: South-Paw/action-netlify-deploy@v1.2.1
        with:
          github-token: ${{ secrets.CI_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.DEV_NETLIFY_SITE_ID }}
          build-dir: "./public"
          config-path: "./netlify.toml"
          comment-on-commit: true