name: CI
on:
  push:
    branches: [netlify]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          version: 14.x
      - name: Install yarn
        run: npm install -g yarn
      - name: Build site
        working-directory: ./
        run: |
          yarn install 
          yarn build
      - name: Netlify deployment
        uses: nwtgck/actions-netlify@v1.2.2
        with:
          publish-dir: "./public"
          production-branch: main
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
