name: Test workflow

on:
  pull_request:
    branches:
      - dev
      - netlify

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 11

      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm lint

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install: false
          build: pnpm build
          start: pnpm preview -- --host 0.0.0.0 --port 4321
          wait-on: "http://localhost:4321/fr/home"
          config: baseUrl=http://localhost:4321
          wait-on-timeout: 900
          browser: chrome
          headed: true

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
