#  Name of workflow
name: Test workflow

# Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - dev
      - netlify

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v2
      # Install NodeJS
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.x
      # Build the app using cypress
      - name: Install yarn
        run: npm install -g yarn
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          DEBUG: "@cypress/github-action"
        with:
          build: yarn run build
          start: yarn run dev
          wait-on: http://localhost:8000
          browser: chrome
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
