#  Name of workflow
name: Test workflow

# Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - dev
      - netlify

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-18.04
    container: cypress/browsers:node14.17.0-chrome91-ff89
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: yarn run build
          start: yarn run serve
          wait-on: "http://localhost:9000/fr/home"
          wait-on-timeout: 900
          browser: chrome
          headed: true
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos