#  Name of workflow
name: Test workflow

# Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - dev
      - netlify

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.5.0-chrome94-ff93
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v2
      - run: chown -R 1001:1001 /github/home/.cache && echo "pwn dat cache"
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn run dev
          wait-on: "http://localhost:8000"
          wait-on-timeout: 900
          browser: chrome
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
