#  Name of workflow
name: Test workflow

# Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - dev
      - netlify

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.13.2-chrome100-ff98
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v3.1.0
        with:
          command-prefix: yarn dlx
          build: yarn run build
          start: yarn run serve
          wait-on: "http://localhost:9000/fr/home"
          config: baseUrl=http://localhost:9000
          wait-on-timeout: 900
          browser: chrome
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos